run:
  deadline: 5m
  build-tags:
    - glfw
    - sdl

linters:
  enable:
    - whitespace
    - godot
    - godox
    - golint

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  exclude:
    # There is a lot of pointer-mangling happening here, so disable this govet warning
    - possible misuse of unsafe.Pointer
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue

linters-settings:
  lll:
    line-length: 160
