run:
  deadline: 5m
  build-tags:
    - glfw
    - sdl

skip-dirs:
  - internal/renderers/gl

linters:
  # Take an aggressive approach: enable everything and only disable if not useful.
  # So far there are fewer to disable than to enable explicitly.
  enable-all: true

  # linters are disabled if their majority of issues is considered false-positive (intended code)
  # and the remaining issues (if existing) aren't worth it.
  disable:
    - gochecknoglobals
    - gocognit # disabled because of the high complexity of demo files
    - goimports # disabled because of so many false-positives with "imgui-go"
    - gofumpt # disabled because no extra need
    - gosec
    - maligned
    - nestif # disabled because of the high complexity of demo files
    - gomnd # disabled as most OpenGL stuff are direct constants.
    - funlen # disabled because of example code. While people will probably tend to duplicate this, they'll handle it on their own.
    - wsl # this one became too pedantic and with a different style than I would.

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  exclude:
    # There is a lot of pointer-mangling happening here, so disable this govet warning
    - possible misuse of unsafe.Pointer
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue

linters-settings:
  lll:
    line-length: 160
