run:
  deadline: 5m
  build-tags:
    - glfw
    - sdl

linters:
  enable-all: true

  # linters are disabled if their majority of issues is considered false-positive (intended code)
  # and the remaining issues (if existing) aren't worth it.
  disable:
    - gochecknoglobals
    - goimports # disabled because of so many false-positives with "imgui-go"
    - gosec
    - maligned
    - funlen # disabled because of example code. While people will probably tend to duplicate this, they'll handle it on their own.
    - godox # for the deliberate TODO tags
    - wsl # this one became too pedantic and with a different style than I would.

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  exclude:
    # There is a lot of pointer-mangling happening here, so disable this govet warning
    - possible misuse of unsafe.Pointer
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue

linters-settings:
  lll:
    line-length: 160

service:
  golangci-lint-version: 1.27.x
  prepare:
    - apt-get update && apt-get install -y mesa-utils mesa-common-dev libsdl2-dev libglfw3-dev
    # the following a fix as per https://github.com/golangci/golangci/issues/29#issuecomment-460649402 -- missing vendor libraries
    - GO111MODULE=on go mod vendor
    # the following a fix as per https://github.com/esimov/diagram/issues/7#issuecomment-443186458 -- glfw library broken through vendoring
    - GO111MODULE=off go get -u github.com/go-gl/glfw/v3.2/glfw/glfw; cp -R $GOPATH/src/github.com/go-gl/glfw/v3.2/glfw/glfw vendor/github.com/go-gl/glfw/v3.2/glfw/glfw
